# Generated by Django 4.2.11 on 2024-08-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_name",
                    models.CharField(max_length=100, verbose_name="статья"),
                ),
                (
                    "article_content",
                    models.TextField(blank=True, null=True, verbose_name="содержание"),
                ),
                (
                    "article_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="image_article/",
                        verbose_name="превью",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="дата создания"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликовано"),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="просмотры"),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
